// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt5wTxS8a29Fq3KCVBPqheYsQU-8QGOo4',
    appId: '1:360144601887:web:f9cfec4242273f0d2c662a',
    messagingSenderId: '360144601887',
    projectId: 'e-ticket-26ac8',
    authDomain: 'e-ticket-26ac8.firebaseapp.com',
    storageBucket: 'e-ticket-26ac8.appspot.com',
    measurementId: 'G-F3L21DLQ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVw7R1N7CBmJtctWXr3EtQZo09jRJus-c',
    appId: '1:360144601887:android:de4955bebac14aed2c662a',
    messagingSenderId: '360144601887',
    projectId: 'e-ticket-26ac8',
    storageBucket: 'e-ticket-26ac8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1lplZd6o_WeHdoUJXIDfzOS62OHtinc',
    appId: '1:360144601887:ios:9d883823376b355b2c662a',
    messagingSenderId: '360144601887',
    projectId: 'e-ticket-26ac8',
    storageBucket: 'e-ticket-26ac8.appspot.com',
    iosBundleId: 'com.example.eTicket',
  );
}
